title: "Loan Approval Predictor"
author: "Prathamesh Kishor Gadgil"
logo: ""
execute:
  execute_notebooks: "off"

myst_enable_extensions:
  - linkify
  - jupyter

html:
  output_folder: docs
  baseurl: /Loan_classification_book/
  use_repository_button: true

repository:
  url: https://github.com/Pgadgil12/Loan_classification.git
  path_to_book: ./
  branch: main



